services:

  loki:
      image: grafana/loki:latest
      container_name: loki
      restart: always
      user: "0:0"  # ISSO NÂO VAI EM PRODUÇÂO, TEM QUE TIRAR
      ports:
        - 3100:3100
        - 7946
        - 9095

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    entrypoint:
      - sh 
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server /data --console-address ':9001'
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=++loki++
    # command: server /data --address ':9000' --console-address ':9001'
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 3

  # bucket:
  #   image: minio/mc:latest
  #   container_name: bucket
  #   depends_on:
  #     minio:
  #       condition: service_healthy
  #   entrypoint: >
  #     /bin/sh -c "
  #       /usr/bin/mc alias set minio http://minio:9000 loki ++loki++
  #       /usr/bin/mc rm -r --force minio/loki || true;
  #       /usr/bin/mc mb minio/loki;
  #       /usr/bin/mc anonymous set public minio/loki;
  #       exit 0;
  #       "


  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    restart: always
    command: ["-config.file=/etc/tempo.yml"]
    expose:
      - 3200
      - 4317
      - 4318
    volumes:
      - ./config/tempo/tempo.yml:/etc/tempo.yml


  otel:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel
    restart: always
    ports:
      - 4317:4317 #gRPC
      - 4318:4318 #http
      - 8888:8888 #prometheus-collector
      - 8889:8889 #prometheus-exporter
      - 1888:1888 #pprof
      - 1313:1313 #health check
      - 55679:55679 #zpages
    command: ["--config=/etc/otelcol/config.yml"]
    volumes:
      - ./config/otel/otel.yml:/etc/otelcol/config.yml
    depends_on:
      - loki
      - tempo
      - mimir
      - grafana


  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
    command: ["-config.file=/etc/promtail/config.yml"]


  mimir:
   image: grafana/mimir:latest
   container_name: mimir
   restart: always
   ports:
     - 9008:9008
     - 9009:9009
   command: ["-config.file=/etc/mimir.yml"]
   volumes:
     - ./config/mimir/mimir.yml:/etc/mimir.yml



  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    restart: always
    command: ["--web.enable-remote-write-receiver", "--config.file=/etc/prometheus/prometheus.yml"]
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - 3001:3000
    volumes:
      - ./config/grafana/datasources.yml:/etc/grafana/provisioning/datasources.yml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_FORM_LOGIN=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    depends_on:
      - loki
      - tempo
      - prometheus
      - mimir
  
volumes:
  minio-data: