auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100

schema_config:
  configs:
    - from: 2025-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

limits_config:
  discover_log_levels: true

common:
  path_prefix: /loki
  replication_factor: 1
  compactor_address: http://loki:3100
  storage:
    s3:
      endpoint: http://minio:9000
      insecure: true
      bucketnames: loki-data
      access_key_id: loki
      secret_access_key: ++loki++
      s3forcepathstyle: true
  ring:
    kvstore:
      store: memberlist

memberlist:
  join_members:
    - loki
  abort_if_cluster_join_fails: false
  max_join_backoff: 1m
  min_join_backoff: 1s
  max_join_retries: 10
  bind_addr: ['0.0.0.0']
  bind_port: 7946

ruler:
  storage:
    s3:
      bucketnames: loki-ruler
